### ISSUE TITLE
[1주차] Clean_Code_1-2장_김주영

### ISSUE THREAD

**Issue by kjy-asl** [2024-BookStudy/bookmark#14]
## 이슈 1. 코드 감각을 기르는 가장 효과적인 방법은 무엇일까?

1장을 읽다 보니 개발 할 때 클린 코드를 유지하는 것은 웬만한 내공이 있지 않은 한 어려울 것 같다는 생각이 듭니다.
사실 클라이언트 요구사항을 맞추기 위해서 인력, 시간이 부족한 상황에서는 책에서 언급한 내용들을 지켜가며 코딩하기 많이 어려울 것 같아요. 결국 일을 착수하기 전까지 프로그래밍 역량을 기르는 것이 가장 중요하다 생각하는데..
저는 공부를 정말 싫어하는 사람이라서 공부를 많이 하기보다는 최적의 공부법을 찾는 것에 더 많은 시간을 쏟곤 합니다. => 공부 안하고 딴 짓 한다는 뜻
여러분은 책에서 언급한 클린코드를 위한 '코드 감각'을 기르는 데 가장 효과적인 방법이 무엇이라 생각하시나요?
ex) 잘 작성된 코드를 많이 보는 것. 코드 작성할 때 깊게 고민하기 등

## 이슈 2. 협업 과정에서 어떻게 클린 코드를 적용해야 하나?

1,2 장을 읽고 해당 내용을 적용해보고자 하는데.. 내가 맡은 작은 부분에 적용하는건 쉽겠지만 프로젝트 전체적으로 적용하고 싶을 땐 어떻게 해야할까요?

**Comment by find11570** [comment]
1. 하나를 제대로 만들고 그냥 손에 익을 때까지 계속.. 반복하면 됩니다.
저는 주로 기본 템플릿을 복사해서 많이 사용했어서 문법이 계속 헷갈릴 때가 있긴 했는데 그것도 반복하면 손이든 머리든 익어버려서 뭔가 다를 때 묘한 기시감을 느끼더라구요... 의식을 무의식으로 바꾸는 (무서운) 방법.  하지만 오래 쉬면 망각한다는.. 단점

2. 제일 간단한 방법은 어떠한 명확한 기준을 가진 누군가가 뼈대를 세워주는 게 제일 빠른 것 같긴 합니다. 
협업의 취지를 살려보자면 구성원/팀원 간 서로 코드 규칙을 정해 최소한의 강제성을 부여해보는 것은 어떨까요?

**Comment by chuseok** [comment]
## Q1
저는 주로 다른 사람의 코드를 많이 보는 방법으로 감각을 익히고 있습니다!
실제로 효과가 있었고 귀찮고 시간이 많이 걸린다고 생각할 수 있지만 코드 리뷰를 하는 문화를 만드는 것도 좋은 방법이라고 생각합니다.
## Q2
한 사람이 바꿀 수 없다고 생각합니다. 계속해서 다같이 규칙을 정의하고 정리하고 자세히 들여다보는 시간을 꾸준히 투자해서 반영할 수 있도록 해서 강제성을 부여해야 한다고 생각합니다.

**Comment by lee-JunR** [comment]
### Q1

1. 오픈 소스에 기여를 도전해보는 것….은 너무나 거창한 방법 
2. (백문이 불여일타지만…) 잘 정리된 오픈소스를 읽어보는 방법이 가장 정석적인 방법이라고 생각이 드네요!
3. (제가 생각했던 방법은) 코딩테스트에 의도적으로 클린코드를 적용해가며 코딩해보는것은 어떨까요?
4. input과 output이 정해져있고 프로그래머스같은 경우 요구사항도 현실적으로 정의되어있어서 클린코드 감각을 키우기 최고의 예제일것 같다는 생각이 들었네요!

### Q2
1. (할 수 있다면!) 경험이 많은 분이 뼈대를 세우고 
2. PR 하기 전에 서로 리뷰를 다는 형식이 가장 좋을 것 같습니다!

**Comment by GaHee99** [comment]
1,저는 솔직히 쉬는 시간에 코드 능력을 기르일이라고 생각해요!! 그거 빼면 시간이 없어요:.

2. 각자아 아는 내용에 대해서 합의가 필요할 것 같아요....

**Comment by cheongwonyoung** [comment]
1. 주영님 예시대로 잘 작성된 코드를 많이 보는 것이 좋다고 생각합니다. 
추가로 제가 아직 클린코드를 생각하며 코딩을 시도하지 못했지만, 내가 작성한 코드를 gpt를 사용하여 클린코드의 방향성과 맞게 리펙토링한 후 다시 본다면 나의 코드의 잘못된 방향이 직관적으로 보일 것 같습니다!(불필요한 명명 등)

2. 기본적인 틀을 함께 세우고, 팀원들과의 지속적인 코드리뷰를 통해 프로젝트가 나쁜 코드로 향하지 않도록 방지해야 할 것 같습니다.
