### ISSUE TITLE
[2주차] Clean_Code_3-4장_최한솔

### ISSUE THREAD

**Issue by chuseok** [2024-BookStudy/bookmark#18]
이슈 1. 3장. 함수에서 추상화를 고려해서 코드를 작성하라는 말이 자주 언급되고 있는데요,
여러분들은 프로젝트를 진행할 때 Repository에 관련된 인터페이스 이외에 추상화 인터페이스나 추상화 클래스를 사용해서 코드를 적절히 분리하셨는지 궁금합니다!

**Comment by lee-JunR** [comment]
저는 잘 못했었던 것 같습니다. 이유는 객체의 책임과 관계를 설정하는데 서툴렀기 때문이 아닌가 하는 생각이 드네요..
책에서 말한 같은 추상화 수준을 맞추기 위해서는 일단 객체의 책임과 관계를 명확히 정의하는 것이 선행되어야 추상화 인터페이스와 클래스를 사용하여 코드의 모듈성을 높이고, 함수의 추상화 수준을 일관되게 유지할 수 있을 것 같습니다.

**Comment by GaHee99** [comment]
저는 다양한 소셜로그인을 처리하기 위해서 **로그인, 로그아웃** 부분을 인터페이스로 만들어서 구현했습니당,
현재로서 생각나는 부분은, '같은 일을 처리하는 다른 방법들'에 대해서 인터페이스를 선언하려고 해요.!
ex) 저장소 cloud를 s3에서 네이버 클라우드로 변경하는 등,, 

추상 클래스 같은 경우는 상속시에 꼭 해야 하는 일을 강제할 때 주로 사용해야할 것 같은데, 아직 제 프로젝트에 한해서는 고려하기 어려웠네용,,
아마 결제시스템같은거를 도입할 때 해볼 것 같슴당~

**Comment by kjy-asl** [comment]
추상화에 대해 한솔님 말씀을 듣고 책을 읽으며 처음 고민하게 되었는데, 지금까지 중요하게 생각을 하지 않았던 이유는 명확한 개념 정립이 안되었기 때문이라고 생각합니다. 한솔님덕에 이번 기회를 통해 확실하게 정리하고 넘어갈 수 있을 것 같네욥

**Comment by cheongwonyoung** [comment]
저는 보통 인터페이스를 활용해서 서비스 로직을 구현했습니다. 
하나의 기능에 해당하는 부분을 인터페이스로 만들고 실질적인 기능을 인터페이스를 통해 구현하였습니다.
하지만 추상클래스까지 활용해가며 프로젝트를 구현해보지는 못한 거 같습니다
