### ISSUE TITLE
[3주차] Clean_Code_5-6장_김현수

### ISSUE THREAD

**Issue by find11570** [2024-BookStudy/bookmark#31]
DTO에서 데이터를 조작할 때 getter, setter를 사용하면서 항상 데이터를 직접적으로만 가져와서 사용했었는데 그러다보니 대부분이 내부 구조를 드러내는 형태로 설계했던 것 같습니다. 혹시 해당 방법을 지켜서 추상화 하여 구현해보신 분이 있으신가요?? 예제에 있는 내용은 이해가 가는데 역으로 직접 데이터를 추상화해서 내부 내용을 숨기려고 하니 막상 이름 짓는 것 만큼 떠오르지가 않네요 각자가 생각한 예시나 경험이 있으면 공유해주세요!

**Comment by GaHee99** [comment]
제가 읽은 바로는, DTO는 굳이 추상화를 하지 않아도 된다! 라는 결론이었습니다.
왜냐하면 DTO자체가, 이미 특수한 필드들만 갖고오는 구조이고, DTO는 말 그대로 Data transfer Object이기 때문입니다!
(정말 단순히 제 생각)

**Comment by find11570** [comment]
앗 제가 이슈를 잘못 적었네요 ! DTO 데이터 조작 시 get,set 했던 방식을 그대로 따와서 다른 데이터 객체 조작 시에도 숨기려고 생각하지 않고 내부구조를 드러내는 형태로 자료구조를 작성했다..! 로 이해해주시면 감사하겠습니다 ㅠ
