### ISSUE TITLE
[4주차] Clean_Code_7-10장 최가희

### ISSUE THREAD

**Issue by GaHee99** [2024-BookStudy/bookmark#45]
### 7장 오류 처리
외부 API사용시, 외부 API Failure에 대한 에러코드들을 열거, 나열하는 것 보다, 외부 API감싸는 것을 더욱 추천하더라구요,
저는 이 부분 읽고 큰 도움이 됐는데, 혹시 다른분들은 외부API 에러처리들을 평소에 어떻게 처리하셨었는지 궁금해요!

### 9장 단위테스트
ㅜ 단위테스트 잘 작성할 수 있는 팁이나, 아니면 책,강의 아시는분? 제발 추천해주십쇼

**Comment by lee-JunR** [comment]
### Q1. 7장 
저는 부끄럽지만 유지보수가 중요한 프로젝트를 맡아본 적이 없어서 이번 책을 보고 아 학습테스트의 중요성과 외부 api, 라이브러리들과의 경계를 명확히 나누는 테크닉들을 배워 공유해드릴 경험적인 내용이 없네요!
### Q2. 9장 
단위테스트... NextStep의 강의 추천드립니다! 저는 다른 과정은 비싸서 `자바 플레이그라운드 with TDD, 클린 코드`만 들었는데 해당 강의가 입문용으로 정말 좋은 것 같더라구요!
입문 이상은...잘 모르겠습니다 팁이라면 해당 강의에 나왔던 내용인데 코딩 테스트같은 입출력이 명확한 항목들에 대해 TDD를 작성해보면 실력이 쭉쭉 는다고 하더라구요!

**Comment by find11570** [comment]
**7장**
저는 개인적으로 유저 시나리오에 따라서 테스트를 구현했었어서,, 
기본적으로 테스트를 통과하면 외부 API에서 사용하고 정의하는 예제 그대로 사용했던 것 같네요..  
외부 API를 감싸 오류 코드를 던지는 코드는 백엔드에서 작성하다보니 경험이 없네요ㅠ 추후 개발할 떄 이 부분을 인지하고 구현하면 좋을 것 같습니다.

**9장**
저는 주로 온라인에 개제된 컬럼이나 회고에서 정보를 찾아보는 편이라서 유료 컨텐츠를 구매해 본 경험이 없네요 ㅠ 개인적으로는 클린 코드를 읽는 중이라 그런지 이 책 시리즈의 테스트 코드 작성 관련 도서를 읽어보고 싶은 생각이 들더라구요 켄트 벡이라는 분이 이 부분에서 저명하신 분이기도 하고 일관성 있는 내용으로 공부하고 싶은 생각😁
