### ISSUE TITLE
[5주차] Clean_Code_11-13장 최가희

### ISSUE THREAD

**Issue by GaHee99** [2024-BookStudy/bookmark#56]
1. 스프링에서 동시성이슈를 다뤄 보신분 있으신가요??? 궁금합니다.
아니면, 관련 포스팅도 추천 받아요 허허~,,,

**Comment by find11570** [comment]
배달의 민족 개발자 분 중 프로모션 시스템 구현에 있어서
동시성 문제가 발생할 수 있는 아래의 두 부분
- 사용자가 이벤트에 참여하기 위해 이전 참여 이력을 조회하는 부분
- 쿠폰 수량이 감소하는 부분

을 해결하는 방법을 잘 설명해주신 것을 볼 수 있었습니다!

https://techblog.woowahan.com/10795/
