### ISSUE TITLE
[9주차] 업무에 바로 쓰는 SQL 튜닝_2장_김주영

### ISSUE THREAD

**Issue by kjy-asl** [2024-BookStudy/bookmark#81]
### 이슈 1
---
고유 인덱스와 기본키의 차이는 NULL이 입력이 된다 안된다 뿐 인것처럼 책에는 나와있습니다. 근데 인덱스 값으로 NULL이 들어가게 되면 인덱스의 역할을 못하는 것 아닌가요??
인덱스의 역할은 데이터 위치를 식별하고 접근 속도를 높이고자 생성되는 것인데..

**Comment by GaHee99** [comment]
어차피 저장 장소를 기준으로 접근하는 것에 초점을 맞추니까 크게 상관없을 것 같은데..

gpt는 답변이 이렇네용

`인덱스의 역할은 데이터의 물리적 저장 위치를 기준으로 빠르게 접근하는 데 있습니다. NULL 값이 들어가더라도, 인덱스는 여전히 다른 값들에 대해 유효하게 작동하므로 전체적인 성능에 큰 영향을 미치지 않습니다. 다만, NULL 값 자체는 고유한 값으로 인식되지 않기 때문에 고유 인덱스에서는 여러 개의 NULL 값을 허용할 수 있습니다. 예를 들어, UNIQUE 인덱스가 있는 열에 NULL 값을 여러 개 삽입할 수 있지만, 이는 다른 고유한 값들이 중복되지 않도록 보장하는 데 영향을 미치지 않습니다. 이 점만 유의하면 인덱스의 본래 목적을 잘 달성할 수 있습니다.`
