### ISSUE TITLE
[9주차] 업무에 바로 쓰는 SQL 튜닝_2장_김동재

### ISSUE THREAD

**Issue by ehdwoKIM** [2024-BookStudy/bookmark#85]
Driven 테이블이 커질 경우 메모리 사용량 증가로 지연이 발생할 경우
이때 조인 순서를 변경해서 Driving 테이블을 크게 만드는 법도 좋은 해결 방법일까요?

**Comment by GaHee99** [comment]
![스크린샷 2024-08-05 오후 10 31 44](https://github.com/user-attachments/assets/ddcf562c-4daf-4f78-a4c1-953d4eaef177)
